### ISSUE TITLE
media server security

### ISSUE THREAD

**Issue by robotnic** [buddycloud/buddycloud-server-java#313]
If the media server lives at the same domain as the page, we have a security issue.

Everybody is able to post a html (svg) page and the javascript in the page runs with the same permission as the real page. 

Here a demonstration for localStorage spying:
https://buddycloud.org/api/robotnic@buddycloud.org/media/A5Dd2prl9uFS569NnuA1

Solution:
Move the mediaserver to an other domain. For example 
https://media.buddycloud.org
The CORS header should be set to allow access from other domains (no security problem)

**Comment by lloydwatkin** [comment]
Not a channel server issue, but yes very much correct. I'd suggest a PR to the media server to add a security section with this information and then @imaginator could update buddycloud.com deployment instructions?

**Comment by imaginator** [comment]
Well spotted. I'll update the install guide.

S.

**Comment by robotnic** [comment]
Will the media server come back soon?

**Comment by imaginator** [comment]
I'll get it up and running again today...

**Comment by imaginator** [comment]
this is fixed with https://github.com/buddycloud/saltstack/blob/master/salt/buddycloud-media-server/mediaserver.properties.template#L40 and deployed to buddycloud.org. It seems that the the buddycloud-angular-app talks to demo.buddycloud.org for fetching images. The api returns the media endpoint... perhaps better to use that..

**Comment by imaginator** [comment]
fyi: https://media.buddycloud.org/api/simon@buddycloud.org/media/avatar?maxheight=100

**Comment by robotnic** [comment]
Don't get the metadata
https://media.buddycloud.org/api/robotnic@buddycloud.org/media/eE5XICaZ3yj1eKkfYkb7/metadata

**Comment by imaginator** [comment]
well spotted. Investigating...

**Comment by imaginator** [comment]
Really fixed now.  https://media.buddycloud.org/api/simon@buddycloud.org/media/oFtyf6xXMyv0NV9T63Nj/metadata

**Comment by robotnic** [comment]
The security bug is still there:
https://buddycloud.org/api/robotnic@buddycloud.org/media/GwSQlY09OXEnNaXUjHDx
